#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$DIR")"

# project root
cd "$PROJECT_ROOT"

docker-compose run --rm \
    --workdir=/src/instances/mangoweb/api \
    --entrypoint="npm run console-debug" \
    -p 127.0.0.1:4481:9229 \
    api "$@"
