#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CURRENT_DIR="$(pwd)"
RELATIVE_DIR="/src/$(realpath --relative-to="$PROJECT_ROOT" "$CURRENT_DIR")"

# project root
cd "$PROJECT_ROOT"

docker-compose run --rm \
	--workdir=$RELATIVE_DIR \
	--entrypoint=npm \
    api "$@"
